from .activity import ActivityLog
from .agentpurposes import AgentPurpose
from .comments import Comment
from .company_type import CompanyType
from .company import Company
from .contact import Contact
from .contactcompany import ContactCompany
from .contactphonenumbers import ContactsPhoneNumber
from .contactprefrences import ContactsPreferences
from .contactsegmentation import ContactSegmentation
from .contactsociallinks import ContactsSocialLink
from .contactype import ContactType
from ..ngtms.models.departement import Department
from .designations import Designation
from .fieldvariables import FieldVariable
from .menus import Meneus
from .notificationtype import NotificationType
from .priority import Priority
from .project import Project
from .projectype import ProjectTypes
from .purpose import Purpose
from .responsetemplates import ResponseTemplates
from .role import Role
from .rolemenupermission import RoleMenuPermission
from .rolesmenu import RolesMenu
from .shiftypes import ShiftTypes
from .slaconfiguration import SlaConfiguration
from .statusworkflow import StatusWorkflow
from .taskattachments import TaskAttachments
from .tasks import Tasks
from .taskstatus import TaskStatus
from .ticketattachment import TicketAttachment
from .ticketjourney import TicketJourney
from .ticketreplies import TicketReplies
from .tickets import Tickets
from .ticketsource import TicketSource
from .ticketstatus import TicketStatus
from .timesheet import Timesheet
from .timesheetactivities import TimesheetActivities
from .timesheetstatus import TimesheetStatus
from .user_status import UserStatus
from .user import User