from models.user import User
from models.role import Role
from models.ticketstatus import TicketStatus
from models.priority import Priority
from models.ticketsource import TicketSource
from models.slaconfiguration import SlaConfiguration
from models.tickets import Tickets
from models.contact import Contact
from models.departement import Department
from models.menus import Meneus
from models.roles_menu import RolesMenu
from models.responsetemplates import ResponseTemplates
from models.notificationtype import NotificationType
from models.purpose import Purpose
from models.agentpurposes import AgentPurpose
from models.ticketattachment import TicketAttachment
from models.company import Company
from models.company_type import CompanyType